### ISSUE TITLE
No Devices

### ISSUE THREAD

**Issue by SavyR7** [serbanb11/bosch-homecom-hass#8]
Forgive my ignorance, I have installed the integration into Home Assistant (Supervised). I get the pop up to enter my user credentials.

I then get this blank box...

![Image](https://github.com/user-attachments/assets/b88f0cdb-0d35-4130-ac20-09e26cfc8d3a)

Then I get the Success box but then nothing else. The logs show the calls to singlekey ID with status of 200 and also the following

2025-05-03 12:10:10.271 DEBUG (MainThread) [homecom_alt] Requesting https://pointt-api.bosch-thermotechnology.com/pointt-api/api/v1/gateways/, method: get
2025-05-03 12:10:10.342 DEBUG (MainThread) [homecom_alt] Data retrieved from https://pointt-api.bosch-thermotechnology.com/pointt-api/api/v1/gateways/, status: 200

But this just loops and nothing else happens. Am I missing something as part of the initial configuration? I have the HomeCom app set up with 2 devices added (Air Conditioners)

**Comment by serbanb11** [comment]
Hello,
You are not missing anything, normally should find your devices, what air conditioners do you have? Might not be supported by this integration. You can try the python library directly and see what is returned by the gateways API
https://github.com/serbanb11/homecom_alt/blob/main/example.py

**Comment by SavyR7** [comment]
> Hello,
> You are not missing anything, normally should find your devices, what air conditioners do you have? Might not be supported by this integration. You can try the python library directly and see what is returned by the gateways API
> https://github.com/serbanb11/homecom_alt/blob/main/example.py

Hi,

They are the 3000i. Thank you, I'll give the library a go and see what happens.

**Comment by serbanb11** [comment]
Hmm, 3000i should work out of the box, can you check that there is on update available for you device?
Can you share the diagnostics data - redacted?

![Image](https://github.com/user-attachments/assets/0b70b68d-dfa0-4a10-afee-ff6577754ca5)

**Comment by serbanb11** [comment]
Do you have your devices in HomeCom app? Do you see your devices in Settings > Update Devices? 
Do you devices are "Climate Class Series" with a 9 numbers ID and the firmware up to date?

**Comment by serbanb11** [comment]
I've looked in the code and looks like your device is Midea based and has another way of interacting with HomeCom. I've pushed a new version v1.1.8 that will add a new log message to homeassistant output, something like this:
2025-05-17 13:38:11.890 INFO (MainThread) [custom_components.bosch_homecom.config_flow] Devices: [{'deviceId': 'xxxxxxxx', 'deviceType': 'rac'}]

If you see no device then your device is not currently supported by this integration.

**Comment by jensjoachim** [comment]
Hi @serbanb11 
I'm having the exact issue as well. Is there any chance that you add support for 3000i(Midea) in the future?

**Comment by SavDaemon** [comment]
> I've looked in the code and looks like your device is Midea based and has another way of interacting with HomeCom. I've pushed a new version v1.1.9 that will add a new log message to homeassistant output, something like this:
> 2025-05-17 13:38:11.890 INFO (MainThread) [custom_components.bosch_homecom.config_flow] Devices: [{'deviceId': 'xxxxxxxx', 'deviceType': 'rac'}]
> 
> If you see no device then your device is not currently supported by this integration.

Sorry for the delay in replying. Looks like as you mentioned, the device isn't supported as I still get no devices when configuring the application. I have the devices up and running in HA via Matter so from my perspective this can be closed.

**Comment by minecj** [comment]
I am having the same issue with a Bosch Climate 7000i model.  I was able to add it through Matter but the device is not showing up in the integration. Device is added to HomeCom and can be controlled from there. Any suggestions? Not seeing any entries in the supervisor logs for custom_components.bosch_homecom.config_flow either.
